=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::CardsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CardsApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::CardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CardsApi' do
    it 'should create an instance of CardsApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::CardsApi)
    end
  end

  # unit tests for cards_create
  # List of loyalty cards. Each card bounds customer and his account. Several cards can be bound to same customer (customer own several accounts), at the same time several of them can be bound to same account (serveral family cards, for example)
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Card]
  describe 'cards_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cards_delete
  # List of loyalty cards. Each card bounds customer and his account. Several cards can be bound to same customer (customer own several accounts), at the same time several of them can be bound to same account (serveral family cards, for example)
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cards_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cards_deposit
  # \&quot; Manual deposit bonus points to the customer or card.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Card]
  describe 'cards_deposit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cards_emit
  # \&quot; Emit (create) new cards.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Card]
  describe 'cards_emit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cards_list
  # List of loyalty cards. Each card bounds customer and his account. Several cards can be bound to same customer (customer own several accounts), at the same time several of them can be bound to same account (serveral family cards, for example)
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page number within the paginated result set.
  # @return [InlineResponse2002]
  describe 'cards_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cards_partial_update
  # List of loyalty cards. Each card bounds customer and his account. Several cards can be bound to same customer (customer own several accounts), at the same time several of them can be bound to same account (serveral family cards, for example)
  # @param id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Card]
  describe 'cards_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cards_read
  # List of loyalty cards. Each card bounds customer and his account. Several cards can be bound to same customer (customer own several accounts), at the same time several of them can be bound to same account (serveral family cards, for example)
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Card]
  describe 'cards_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cards_update
  # List of loyalty cards. Each card bounds customer and his account. Several cards can be bound to same customer (customer own several accounts), at the same time several of them can be bound to same account (serveral family cards, for example)
  # @param id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Card]
  describe 'cards_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
