=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::CustomersSyncApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomersSyncApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::CustomersSyncApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomersSyncApi' do
    it 'should create an instance of CustomersSyncApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::CustomersSyncApi)
    end
  end

  # unit tests for customers_sync_create
  # Performs synchronization of customer by customizable key fields. By default they are phone number, last name and birth date. If customer with such combination will not be found, it will be created. In other case it will be updated :return: Created or updated customer instance
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'customers_sync_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
