=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::CustomersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomersApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::CustomersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomersApi' do
    it 'should create an instance of CustomersApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::CustomersApi)
    end
  end

  # unit tests for customers_create
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CustomerList]
  describe 'customers_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_delete
  # @param id A unique integer value identifying this клиент.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'customers_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_eid_create
  # Creates or updates customer by external id
  # @param external_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'customers_eid_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_eid_read
  # Returns customer by external identifier
  # @param external_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'customers_eid_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_list
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :id 
  # @option opts [String] :date_created 
  # @option opts [String] :date_modified 
  # @option opts [String] :date_modified__gt 
  # @option opts [String] :date_modified__lt 
  # @option opts [String] :date_modified__gte 
  # @option opts [String] :date_modified__lte 
  # @option opts [String] :ext_date_created 
  # @option opts [String] :ext_date_modified 
  # @option opts [String] :zip 
  # @option opts [String] :country_code 
  # @option opts [String] :country_name 
  # @option opts [String] :region 
  # @option opts [String] :district 
  # @option opts [String] :settlement_type 
  # @option opts [String] :city 
  # @option opts [String] :street 
  # @option opts [String] :house_no 
  # @option opts [String] :building_no 
  # @option opts [String] :flat_no 
  # @option opts [String] :room_no 
  # @option opts [String] :raw_address 
  # @option opts [String] :doc_type 
  # @option opts [String] :doc_issuer_info 
  # @option opts [String] :doc_series 
  # @option opts [String] :doc_number 
  # @option opts [String] :department_code 
  # @option opts [String] :department_name 
  # @option opts [String] :doc_issue_date 
  # @option opts [String] :doc_expiration_date 
  # @option opts [String] :user 
  # @option opts [String] :external_id 
  # @option opts [String] :first_name 
  # @option opts [String] :last_name 
  # @option opts [String] :middle_name 
  # @option opts [String] :phone 
  # @option opts [String] :allow_phone_contact 
  # @option opts [String] :birth_date 
  # @option opts [String] :gender 
  # @option opts [String] :language 
  # @option opts [String] :email 
  # @option opts [String] :allow_email_contact 
  # @option opts [String] :notes 
  # @option opts [String] :is_closed 
  # @option opts [String] :merged_to 
  # @option opts [Integer] :page A page number within the paginated result set.
  # @return [InlineResponse2004]
  describe 'customers_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_partial_update
  # @param id A unique integer value identifying this клиент.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CustomerList]
  describe 'customers_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_read
  # @param id A unique integer value identifying this клиент.
  # @param [Hash] opts the optional parameters
  # @return [CustomerDetail]
  describe 'customers_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customers_update
  # @param id A unique integer value identifying this клиент.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CustomerList]
  describe 'customers_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
