=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::CustomerPreferencesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CustomerPreferencesApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::CustomerPreferencesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerPreferencesApi' do
    it 'should create an instance of CustomerPreferencesApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::CustomerPreferencesApi)
    end
  end

  # unit tests for customer_preferences_create
  # Customer preferences
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CustomerPreferences]
  describe 'customer_preferences_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customer_preferences_delete
  # Customer preferences
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'customer_preferences_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customer_preferences_list
  # Customer preferences
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page number within the paginated result set.
  # @return [InlineResponse2003]
  describe 'customer_preferences_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customer_preferences_partial_update
  # Customer preferences
  # @param id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CustomerPreferences]
  describe 'customer_preferences_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customer_preferences_read
  # Customer preferences
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [CustomerPreferences]
  describe 'customer_preferences_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for customer_preferences_update
  # Customer preferences
  # @param id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [CustomerPreferences]
  describe 'customer_preferences_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
