=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::LoginApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LoginApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::LoginApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LoginApi' do
    it 'should create an instance of LoginApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::LoginApi)
    end
  end

  # unit tests for login_create
  # API View that receives a POST with a user&#39;s username and password.
  # Returns a JSON Web Token that can be used for authenticated requests.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [JSONWebToken]
  describe 'login_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
