=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::OffersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OffersApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::OffersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OffersApi' do
    it 'should create an instance of OffersApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::OffersApi)
    end
  end

  # unit tests for offers_create
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [GetApplicableOffers]
  describe 'offers_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
