=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::OrderItemsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrderItemsApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::OrderItemsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrderItemsApi' do
    it 'should create an instance of OrderItemsApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::OrderItemsApi)
    end
  end

  # unit tests for order_items_create
  # List of services within order
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [OrderItem]
  describe 'order_items_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for order_items_delete
  # List of services within order
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'order_items_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for order_items_list
  # List of services within order
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page number within the paginated result set.
  # @return [InlineResponse2005]
  describe 'order_items_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for order_items_partial_update
  # List of services within order
  # @param id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [OrderItem]
  describe 'order_items_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for order_items_read
  # List of services within order
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [OrderItem]
  describe 'order_items_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for order_items_update
  # List of services within order
  # @param id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [OrderItem]
  describe 'order_items_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
