=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::OrdersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrdersApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::OrdersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrdersApi' do
    it 'should create an instance of OrdersApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::OrdersApi)
    end
  end

  # unit tests for orders_create
  # Presents list of previous and current guest&#39;s orders
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Order]
  describe 'orders_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_delete
  # Presents list of previous and current guest&#39;s orders
  # @param id A unique integer value identifying this заказ.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'orders_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_extra_fields_delete
  # Presents list of previous and current guest&#39;s orders
  # @param id A unique integer value identifying this заказ.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'orders_extra_fields_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_extra_fields_partial_update
  # Presents list of previous and current guest&#39;s orders
  # @param id A unique integer value identifying this заказ.
  # @param name 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Order]
  describe 'orders_extra_fields_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_extra_fields_read
  # Presents list of previous and current guest&#39;s orders
  # @param id A unique integer value identifying this заказ.
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [OrderSerializerNoBinaryFields]
  describe 'orders_extra_fields_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_list
  # Presents list of previous and current guest&#39;s orders
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page number within the paginated result set.
  # @return [InlineResponse2006]
  describe 'orders_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_partial_update
  # Presents list of previous and current guest&#39;s orders
  # @param id A unique integer value identifying this заказ.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Order]
  describe 'orders_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_read
  # Presents list of previous and current guest&#39;s orders
  # @param id A unique integer value identifying this заказ.
  # @param [Hash] opts the optional parameters
  # @return [OrderSerializerNoBinaryFields]
  describe 'orders_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for orders_update
  # Presents list of previous and current guest&#39;s orders
  # @param id A unique integer value identifying this заказ.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Order]
  describe 'orders_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
