=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::PaymentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentsApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::PaymentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentsApi' do
    it 'should create an instance of PaymentsApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::PaymentsApi)
    end
  end

  # unit tests for payments_create
  # List of order&#39;s payments
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Payment]
  describe 'payments_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payments_delete
  # List of order&#39;s payments
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'payments_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payments_list
  # List of order&#39;s payments
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page number within the paginated result set.
  # @return [InlineResponse2007]
  describe 'payments_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payments_partial_update
  # List of order&#39;s payments
  # @param id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Payment]
  describe 'payments_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payments_read
  # List of order&#39;s payments
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Payment]
  describe 'payments_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for payments_update
  # List of order&#39;s payments
  # @param id 
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Payment]
  describe 'payments_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
