=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::PointOfSalesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PointOfSalesApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::PointOfSalesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PointOfSalesApi' do
    it 'should create an instance of PointOfSalesApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::PointOfSalesApi)
    end
  end

  # unit tests for point_of_sales_create
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [PointOfSale]
  describe 'point_of_sales_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for point_of_sales_delete
  # @param id A unique integer value identifying this точка продаж.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'point_of_sales_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for point_of_sales_list
  # @param [Hash] opts the optional parameters
  # @option opts [String] :code 
  # @option opts [String] :name 
  # @option opts [Integer] :page A page number within the paginated result set.
  # @return [InlineResponse2008]
  describe 'point_of_sales_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for point_of_sales_orders_eid_create
  # @param external_id 
  # @param pos_code 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'point_of_sales_orders_eid_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for point_of_sales_orders_eid_read
  # @param external_id 
  # @param pos_code 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'point_of_sales_orders_eid_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for point_of_sales_partial_update
  # @param id A unique integer value identifying this точка продаж.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [PointOfSale]
  describe 'point_of_sales_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for point_of_sales_read
  # @param id A unique integer value identifying this точка продаж.
  # @param [Hash] opts the optional parameters
  # @return [PointOfSale]
  describe 'point_of_sales_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for point_of_sales_update
  # @param id A unique integer value identifying this точка продаж.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [PointOfSale]
  describe 'point_of_sales_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
