=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

require 'spec_helper'
require 'json'

# Unit tests for CheckpointCrmClient::PreferenceCategoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PreferenceCategoriesApi' do
  before do
    # run before each test
    @api_instance = CheckpointCrmClient::PreferenceCategoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PreferenceCategoriesApi' do
    it 'should create an instance of PreferenceCategoriesApi' do
      expect(@api_instance).to be_instance_of(CheckpointCrmClient::PreferenceCategoriesApi)
    end
  end

  # unit tests for preference_categories_create
  # Customer preferences
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [PreferenceCategories]
  describe 'preference_categories_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for preference_categories_delete
  # Customer preferences
  # @param id A unique integer value identifying this категория предпочтений.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'preference_categories_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for preference_categories_list
  # Customer preferences
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page A page number within the paginated result set.
  # @return [InlineResponse2009]
  describe 'preference_categories_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for preference_categories_partial_update
  # Customer preferences
  # @param id A unique integer value identifying this категория предпочтений.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [PreferenceCategories]
  describe 'preference_categories_partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for preference_categories_read
  # Customer preferences
  # @param id A unique integer value identifying this категория предпочтений.
  # @param [Hash] opts the optional parameters
  # @return [PreferenceCategories]
  describe 'preference_categories_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for preference_categories_update
  # Customer preferences
  # @param id A unique integer value identifying this категория предпочтений.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [PreferenceCategories]
  describe 'preference_categories_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
