=begin
#Checkpoint CRM API

#Checkpoint CRM API

The version of the OpenAPI document: v1
Contact: szhizhenko@sanatorium-is.ru
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.2

=end

# Common files
require 'checkpoint-crm-client/api_client'
require 'checkpoint-crm-client/api_error'
require 'checkpoint-crm-client/version'
require 'checkpoint-crm-client/configuration'

# Models
require 'checkpoint-crm-client/models/account'
require 'checkpoint-crm-client/models/account_operation'
require 'checkpoint-crm-client/models/apply_offers'
require 'checkpoint-crm-client/models/card'
require 'checkpoint-crm-client/models/card_for_customer'
require 'checkpoint-crm-client/models/customer_detail'
require 'checkpoint-crm-client/models/customer_list'
require 'checkpoint-crm-client/models/customer_preference_for_customer'
require 'checkpoint-crm-client/models/customer_preferences'
require 'checkpoint-crm-client/models/extra_fields'
require 'checkpoint-crm-client/models/extra_fields_no_binary'
require 'checkpoint-crm-client/models/get_applicable_offers'
require 'checkpoint-crm-client/models/inline_response200'
require 'checkpoint-crm-client/models/inline_response2001'
require 'checkpoint-crm-client/models/inline_response20010'
require 'checkpoint-crm-client/models/inline_response20011'
require 'checkpoint-crm-client/models/inline_response2002'
require 'checkpoint-crm-client/models/inline_response2003'
require 'checkpoint-crm-client/models/inline_response2004'
require 'checkpoint-crm-client/models/inline_response2005'
require 'checkpoint-crm-client/models/inline_response2006'
require 'checkpoint-crm-client/models/inline_response2007'
require 'checkpoint-crm-client/models/inline_response2008'
require 'checkpoint-crm-client/models/inline_response2009'
require 'checkpoint-crm-client/models/json_web_token'
require 'checkpoint-crm-client/models/order'
require 'checkpoint-crm-client/models/order_item'
require 'checkpoint-crm-client/models/order_serializer_no_binary_fields'
require 'checkpoint-crm-client/models/payment'
require 'checkpoint-crm-client/models/point_of_sale'
require 'checkpoint-crm-client/models/preference_categories'
require 'checkpoint-crm-client/models/setting'
require 'checkpoint-crm-client/models/tier'

# APIs
require 'checkpoint-crm-client/api/account_operations_api'
require 'checkpoint-crm-client/api/accounts_api'
require 'checkpoint-crm-client/api/apply_offers_api'
require 'checkpoint-crm-client/api/cards_api'
require 'checkpoint-crm-client/api/customer_preferences_api'
require 'checkpoint-crm-client/api/customers_api'
require 'checkpoint-crm-client/api/customers_sync_api'
require 'checkpoint-crm-client/api/login_api'
require 'checkpoint-crm-client/api/offers_api'
require 'checkpoint-crm-client/api/order_items_api'
require 'checkpoint-crm-client/api/orders_api'
require 'checkpoint-crm-client/api/payments_api'
require 'checkpoint-crm-client/api/point_of_sales_api'
require 'checkpoint-crm-client/api/preference_categories_api'
require 'checkpoint-crm-client/api/settings_api'
require 'checkpoint-crm-client/api/tiers_api'

module CheckpointCrmClient
  class << self
    # Customize default settings for the SDK using block.
    #   CheckpointCrmClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
